AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless, event-sourced "Patience" solitaire card game

Parameters:
  Stage:
    Type: String
    Default: dev
    Description: Name of the stage

Globals:
  Function:
    Runtime: nodejs12.x
    Tracing: Active
  Api:
    TracingEnabled: true
    MethodSettings:
      - LoggingLevel: INFO
        DataTraceEnabled: true
        ResourcePath: '/*'
        HttpMethod: '*'

Resources:
  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  Account:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  GetGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/handlers/http/game
      Handler: get.handler
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          DB_TABLE_EVENTS: !Ref EventsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTable
      Events:
        GetGame:
          Type: Api
          Properties:
            Path: /game/{gameId}
            Method: get

  PostGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/handlers/http/game
      Handler: post.handler
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          DB_TABLE_EVENTS: !Ref EventsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Events:
        PostGame:
          Type: Api
          Properties:
            Path: /game
            Method: post

  PatchGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/handlers/http/game
      Handler: patch.handler
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          DB_TABLE_EVENTS: !Ref EventsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Events:
        PatchGame:
          Type: Api
          Properties:
            Path: /game/{gameId}/{moveType}
            Method: patch

  DeleteGameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/handlers/http/game
      Handler: delete.handler
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          DB_TABLE_EVENTS: !Ref EventsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Events:
        DeleteGame:
          Type: Api
          Properties:
            Path: /game/{gameId}
            Method: delete

  GetAggregatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/handlers/http/aggregates
      Handler: get.handler
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          BUCKET_AGGREGATES: !Ref AggregatesBucket
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref AggregatesBucket
      Events:
        GetAggregates:
          Type: Api
          Properties:
            Path: /aggregates
            Method: get

  RegenerateAggregatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/handlers/http/aggregates
      Handler: regenerate.handler
      ReservedConcurrentExecutions: 5
      Timeout: 60
      Environment:
        Variables:
          DB_TABLE_EVENTS: !Ref EventsTable
          BUCKET_AGGREGATES: !Ref AggregatesBucket
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTable
        - S3WritePolicy:
            BucketName: !Ref AggregatesBucket
      Events:
        RegenerateAggregates:
          Type: Api
          Properties:
            Path: /aggregates/regenerate
            Method: get

  StreamUpdateAggregatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./build/handlers/dynamodb/events
      Handler: stream.handler
      ReservedConcurrentExecutions: 5
      Environment:
        Variables:
          DB_TABLE_EVENTS: !Ref EventsTable
          BUCKET_AGGREGATES: !Ref AggregatesBucket
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref EventsTable
        - S3CrudPolicy:
            BucketName: !Ref AggregatesBucket
      Events:
        EventReceived:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt EventsTable.StreamArn
            Enabled: True
            StartingPosition: LATEST

  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "patience_events_${Stage}"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: gameId
          KeyType: HASH
        - AttributeName: eventTimestamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: gameId
          AttributeType: S
        - AttributeName: eventTimestamp
          AttributeType: N
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  AggregatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "patience-aggregates-${Stage}"
      VersioningConfiguration:
        Status: Enabled

Outputs:
  ApiBaseUrl:
    Description: "API Gateway endpoint base URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  EventsTableName:
    Description: "Name of the events table"
    Value: !Ref EventsTable
